# Generated by Django 4.1.1 on 2022-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(default='🏡'),
        ),
    ]
